### Тема “Создание признакового пространства”

Продолжим обработку данных с Твиттера. 

1. Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'. 
Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().
 
2. Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно.
Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df.
Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000.
Исключим стоп-слова с помощью stop_words='english'.
Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().
 
3. Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [122]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer,HashingVectorizer
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import model_selection, preprocessing, linear_model
from sklearn.metrics import accuracy_score
from stop_words import get_stop_words
import random

In [48]:
stop_words = get_stop_words('en')

In [49]:
combine_df = pd.read_pickle('combine_df.pkl')
combine_df

,id,label,tweet,tweet_clean,tweet_token,tweet_token_filtered,tweet_stemmed,tweet_lemmatized
0,1,0.0,@user when a father is dysfunctional and is s...,when fatheare is dysfyounctional and is so sel...,"[when, fatheare, is, dysfyounctional, and, is,...","[fatheare, dysfyounctional, selfish, dareagare...","[fathear, dysfyounct, selfish, dareagarein, ki...","[fatheare, dysfyounctional, selfish, dareagare..."
1,2,0.0,@user @user thanks for #lyft credit i can't us...,thanks foare lyft careedit cannot youse cayous...,"[thanks, foare, lyft, careedit, can, not, yous...","[thanks, foare, lyft, careedit, youse, cayouse...","[thank, foar, lyft, careedit, yous, cayous, of...","[thanks, foare, lyft, careedit, youse, cayouse..."
2,3,0.0,bihday your majesty,bihday yoyouare majesty,"[bihday, yoyouare, majesty]","[bihday, yoyouare, majesty]","[bihday, yoyouar, majesti]","[bihday, yoyouare, majesty]"
3,4,0.0,#model i love u take with u all the time in ...,model love you take with you all the time in y...,"[model, love, you, take, with, you, all, the, ...","[model, love, take, time, youare]","[model, love, take, time, youar]","[model, love, take, time, youare]"
4,5,0.0,factsguide: society now #motivation,factsgareinyouide society now motivation,"[factsgareinyouide, society, now, motivation]","[factsgareinyouide, society, motivation]","[factsgareinyouid, societi, motiv]","[factsgareinyouide, society, motivation]"
...,...,...,...,...,...,...,...,...
49154,49155,NaN,thought factory: left-right polarisation! #tru...,thoyougareinht factoarey leftareigareinht pola...,"[thoyougareinht, factoarey, leftareigareinht, ...","[thoyougareinht, factoarey, leftareigareinht, ...","[thoyougareinht, factoarey, leftareigareinht, ...","[thoyougareinht, factoarey, leftareigareinht, ..."
49155,49156,NaN,feeling like a mermaid ð #hairflip #neverre...,feelingarein like mearemaid haiareflip neveare...,"[feelingarein, like, mearemaid, haiareflip, ne...","[feelingarein, like, mearemaid, haiareflip, ne...","[feelingarein, like, mearemaid, haiareflip, ne...","[feelingarein, like, mearemaid, haiareflip, ne..."
49156,49157,NaN,#hillary #campaigned today in #ohio((omg)) &am...,hillaarey campaigareinned today in ohiooh my g...,"[hillaarey, campaigareinned, today, in, ohiooh...","[hillaarey, campaigareinned, today, ohiooh, go...","[hillaarey, campaigarein, today, ohiooh, godar...","[hillaarey, campaigareinned, today, ohiooh, go..."
49157,49158,NaN,"happy, at work conference: right mindset leads...",happy at woarek confeareence areigareinht mind...,"[happy, at, woarek, confeareence, areigareinht...","[happy, woarek, confeareence, areigareinht, mi...","[happi, woarek, confear, areigareinht, mindset...","[happy, woarek, confeareence, areigareinht, mi..."
49158,49159,NaN,"my song ""so glad"" free download! #shoegaze ...",my songarein so gareinlad fareee download shoe...,"[my, songarein, so, gareinlad, fareee, downloa...","[songarein, gareinlad, fareee, download, shoeg...","[songarein, gareinlad, faree, download, shoega...","[songarein, gareinlad, fareee, download, shoeg..."

#### Задание 1  
Создайте мешок слов с помощью sklearn.feature_extraction.text.CountVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно. Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df. Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000. Исключим стоп-слова с помощью stop_words='english'. Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью CountVectorizer.get_feature_names().

In [50]:
# создадим веторайзер с нужными кроитериями
count_vectorizer_lemmatized = CountVectorizer(max_df=0.9,max_features = 1000,stop_words=stop_words)
count_vectorizer_stemmed = CountVectorizer(max_df=0.9,max_features = 1000,stop_words=stop_words)

In [57]:
# Очистим от стоп слов и создадим корпус для векторайзера
corpus_lim = combine_df.tweet_lemmatized.apply(lambda x: ', '.join(x))
corpus_lim

0        fatheare, dysfyounctional, selfish, dareagarei...
1        thanks, foare, lyft, careedit, youse, cayouse,...
2                                bihday, yoyouare, majesty
3                          model, love, take, time, youare
4                   factsgareinyouide, society, motivation
                               ...
49154    thoyougareinht, factoarey, leftareigareinht, p...
49155    feelingarein, like, mearemaid, haiareflip, nev...
49156    hillaarey, campaigareinned, today, ohiooh, god...
49157    happy, woarek, confeareence, areigareinht, min...
49158    songarein, gareinlad, fareee, download, shoega...
Name: tweet_lemmatized, Length: 49159, dtype: object

In [59]:
corpus_stem = combine_df.tweet_stemmed.apply(lambda x: ', '.join(x))
corpus_stem

0        fathear, dysfyounct, selfish, dareagarein, kid...
1        thank, foar, lyft, careedit, yous, cayous, off...
2                                 bihday, yoyouar, majesti
3                           model, love, take, time, youar
4                         factsgareinyouid, societi, motiv
                               ...
49154    thoyougareinht, factoarey, leftareigareinht, p...
49155    feelingarein, like, mearemaid, haiareflip, nev...
49156    hillaarey, campaigarein, today, ohiooh, godare...
49157    happi, woarek, confear, areigareinht, mindset,...
49158    songarein, gareinlad, faree, download, shoegar...
Name: tweet_stemmed, Length: 49159, dtype: object

In [60]:
# создадим bag_of_words
bag_of_words_lemmatized = count_vectorizer_lemmatized.fit_transform(corpus_lim)
bag_of_words_stem = count_vectorizer_stemmed.fit_transform(corpus_stem)
bag_of_words_lemmatized.get_shape(),bag_of_words_stem.get_shape()

((49159, 1000), (49159, 1000))

In [77]:
# датафрейм с лемитизацией
feature_names = count_vectorizer_lemmatized.get_feature_names()
count_vectorizer_lemmatized_df = pd.DataFrame(bag_of_words_lemmatized.toarray(), columns = feature_names)
print(count_vectorizer_lemmatized_df.sum().sort_values(ascending = False))
count_vectorizer_lemmatized_df

yoyou             9179
foare             7002
see               5927
love              4499
day               4360
                  ...
gareinearemany      63
manyousi            63
tea                 63
areoome             63
areelease           63
Length: 1000, dtype: int64

,aareareived,aaree,aareoyound,able,aboyout,absolyoutely,accoyount,act,action,actoare,...,yoyoultyouaree,yoyoultyouareeofdevelopment,yoyoungarein,yoyous,yoyoustomeare,yoyoustomeares,yoyout,yoyoute,yoyoutyoube,yyoummy
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49155,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49157,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
49158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
# датафрейм с stem
feature_names = count_vectorizer_stemmed.get_feature_names()
count_vectorizer_stem_df = pd.DataFrame(bag_of_words_stem.toarray(), columns = feature_names)
print(count_vectorizer_stem_df.sum().sort_values(ascending = False))
count_vectorizer_stem_df

yoyou           9266
foar            7009
see             5927
love            4935
day             4360
                ...
eqyoual           66
seeioyou          66
winnear           66
million           66
fingareinear      66
Length: 1000, dtype: int64

,aare,aareareiv,aareoyound,abl,aboyout,absolyout,accept,accoyount,act,action,...,yoyouarear,yoyouareself,yoyoultyouare,yoyoultyouareeofdevelop,yoyoungarein,yoyoup,yoyous,yoyoustomear,yoyout,yoyoutyoub
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49155,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49156,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49157,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
49158,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

2/ Создайте мешок слов с помощью sklearn.feature_extraction.text.TfidfVectorizer.fit_transform(). Применим его к 'tweet_stemmed' и 'tweet_lemmatized' отдельно. Игнорируем слова, частота которых в документе строго превышает порог 0.9 с помощью max_df. Ограничим количество слов, попадающий в мешок, с помощью max_features = 1000. Исключим стоп-слова с помощью stop_words='english'. Отобразим Bag-of-Words модель как DataFrame. columns необходимо извлечь с помощью TfidfVectorizer.get_feature_names().

In [83]:
# создадим веторайзер с нужными кроитериями
tfidf_vectorizer_lemmatized = TfidfVectorizer(max_df=0.9,max_features = 1000,stop_words=stop_words)
tfidf_vectorizer_stemmed = TfidfVectorizer(max_df=0.9,max_features = 1000,stop_words=stop_words)

In [84]:
# создадим bag_of_words
bag_of_words_lemmatized_tfidf = tfidf_vectorizer_lemmatized.fit_transform(corpus_lim)
bag_of_words_stem_tfidf  = tfidf_vectorizer_stemmed.fit_transform(corpus_stem)
bag_of_words_lemmatized_tfidf.get_shape(),bag_of_words_stem_tfidf.get_shape()

((49159, 1000), (49159, 1000))

In [86]:
# датафрейм с лемитизацией
feature_names = tfidf_vectorizer_lemmatized.get_feature_names()
tfidf_vectorizer_lemmatized_df = pd.DataFrame(bag_of_words_lemmatized_tfidf.toarray(), columns = feature_names)
print(tfidf_vectorizer_lemmatized_df.sum().sort_values(ascending = False))
tfidf_vectorizer_lemmatized_df

yoyou             1852.918078
foare             1609.407277
see               1432.036516
day               1261.175353
love              1224.517841
                     ...
nayougareinhty      26.594030
hoareny             26.527919
expanse             26.496495
kinky               25.087397
leakagareine        22.588018
Length: 1000, dtype: float64

,aareareived,aaree,aareoyound,able,aboyout,absolyoutely,accoyount,act,action,actoare,...,yoyoultyouaree,yoyoultyouareeofdevelopment,yoyoungarein,yoyous,yoyoustomeare,yoyoustomeares,yoyout,yoyoute,yoyoutyoube,yyoummy
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.308796,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [87]:
# датафрейм с stem
feature_names = tfidf_vectorizer_stemmed.get_feature_names()
tfidf_vectorizer_stemmed_df = pd.DataFrame(bag_of_words_stem_tfidf.toarray(), columns = feature_names)
print(tfidf_vectorizer_stemmed_df.sum().sort_values(ascending = False))
tfidf_vectorizer_stemmed_df

yoyou             1837.373361
foar              1566.554077
see               1397.221048
love              1290.159506
day               1244.898359
                     ...
blyouar             27.600112
nayougareinhti      26.612573
hoareni             26.559602
matearei            26.352483
kinki               25.223190
Length: 1000, dtype: float64

,aare,aareareiv,aareoyound,abl,aboyout,absolyout,accept,accoyount,act,action,...,yoyouarear,yoyouareself,yoyoultyouare,yoyoultyouareeofdevelop,yoyoungarein,yoyoup,yoyous,yoyoustomear,yoyout,yoyoutyoub
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49154,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
49155,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
49156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
49157,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.310822,0.0,0.0,0.0,0.0,0.0,0.0
49158,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

Проверьте ваши векторайзеры на корпусе который использовали на вебинаре, составьте таблицу метод векторизации и скор который вы получили (в методах векторизации по изменяйте параметры что бы добиться лучшего скора) обратите внимание как падает/растёт скор при уменьшении количества фичей, и изменении параметров, так же попробуйте применить к векторайзерам PCA для сокращения размерности посмотрите на качество сделайте выводы

In [88]:
# Загружаем данные
with open('corpus','r') as f:
    data = f.read()
labels, texts = [], []
for  line in data.split("\n"):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

# создаем df
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

                                                text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [89]:
train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'])

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

In [99]:
def testing(vectorizer,model=LogisticRegression()):
    vectorizer.fit(trainDF['text'])

    xtrain =  vectorizer.transform(train_x)
    xvalid =  vectorizer.transform(valid_x)

    model.fit(xtrain, train_y)
    predictions = model.predict(xvalid)
    
    return accuracy_score(valid_y, predictions)

In [102]:
# Проверим как работает
vec = TfidfVectorizer(max_df=0.9,max_features = 100,stop_words=stop_words)

testing(vec)

0.7248

In [135]:
max_df = [1,0.95,0.9,0.85,0.8,0.75,0.7]
min_df = [1,2,5,8,10,15,25,30,40,50]
max_features = [None,100,500,1000,2000,5000,10000,15000,20000,25000]
ngram_range=[(1, 1),(1,2),(2,2),(1,3),(2,3),(3,3)]

In [141]:
def choice():
    ma_df = np.random.choice(max_df)
    mi_df = np.random.choice(min_df)
    m_features = np.random.choice(max_features)
    n_range = random.choice(ngram_range)
    key = str(ma_df)+'_'+str(mi_df) +"_" +str(m_features) + '_'+str(n_range)
    return key,ma_df,mi_df, m_features, n_range

In [144]:
%%time
d={}
count = 1000
for _ in range(count):
    for i in range(5):
        key,ma_df,mi_df, m_features, n_range = choice()
        if key in d:
            continue
        else:
            break
    vec = TfidfVectorizer(max_df=ma_df,min_df =mi_df, max_features = m_features,ngram_range = n_range ,stop_words=stop_words) 
    d[key] = testing(vec)

Wall time: 35min 21s

In [148]:
%%time
d_2={}
count = 1000
for _ in range(count):
    for i in range(5):
        key,ma_df,mi_df, m_features, n_range = choice()
        if key in d_2:
            continue
        else:
            break
    vec = CountVectorizer(max_df=ma_df,min_df =mi_df, max_features = m_features,ngram_range = n_range ,stop_words=stop_words) 
    d_2[key] = testing(vec)

Wall time: 36min 5s

In [155]:
result = pd.DataFrame()
for  k,r in d.items():
    my_row = {'vectoreiz':'tfidf','param':k,'accuracy':r}
    result = result.append(my_row,ignore_index=True)
for  k,r in d_2.items():
    my_row = {'vectoreiz':'count','param':k,'accuracy':r}
    result = result.append(my_row,ignore_index=True)    
result.sort_values('accuracy',ascending = False,inplace = True)

In [161]:
result.head(50)

      accuracy                param vectoreiz
912     0.8668   1.0_1_25000_(1, 3)     tfidf
599     0.8668  0.75_2_25000_(1, 2)     tfidf
831     0.8660   0.7_2_25000_(1, 3)     tfidf
135     0.8660   0.8_2_25000_(1, 3)     tfidf
608     0.8660   0.9_2_25000_(1, 3)     tfidf
780     0.8656   0.9_2_10000_(1, 3)     tfidf
49      0.8656   0.9_1_10000_(1, 3)     tfidf
130     0.8656   0.7_1_10000_(1, 3)     tfidf
301     0.8656  0.75_1_10000_(1, 3)     tfidf
63      0.8652   0.85_8_None_(1, 3)     tfidf
592     0.8652   0.9_8_20000_(1, 3)     tfidf
430     0.8652  0.85_2_20000_(1, 3)     tfidf
661     0.8652   1.0_2_20000_(1, 3)     tfidf
691     0.8652  0.95_8_20000_(1, 3)     tfidf
567     0.8652   1.0_8_20000_(1, 3)     tfidf
140     0.8652   0.7_8_10000_(1, 3)     tfidf
158     0.8652   0.7_2_20000_(1, 3)     tfidf
879     0.8652   0.7_8_15000_(1, 3)     tfidf
576     0.8652  0.75_8_20000_(1, 3)     tfidf
882     0.8652  0.75_2_20000_(1, 3)     tfidf
147     0.8648  0.95_2_20000_(1, 2)     tfidf
559     0.8648   0.9_2_20000_(1, 2)     tfidf
418     0.8648  0.95_1_15000_(1, 2)     tfidf
395     0.8648  0.75_1_15000_(1, 2)     tfidf
529     0.8648   1.0_1_15000_(1, 2)     tfidf
643     0.8648   1.0_2_15000_(1, 3)     tfidf
371     0.8648  0.95_2_15000_(1, 2)     tfidf
461     0.8648   0.9_2_15000_(1, 2)     tfidf
861     0.8648   0.7_1_15000_(1, 2)     tfidf
483     0.8648  0.85_2_20000_(1, 2)     tfidf
538     0.8644  0.85_8_15000_(1, 2)     tfidf
707     0.8644   1.0_8_15000_(1, 2)     tfidf
385     0.8644   0.8_1_25000_(1, 2)     tfidf
812     0.8644  0.95_5_20000_(1, 2)     tfidf
252     0.8644  0.95_5_25000_(1, 2)     tfidf
505     0.8644   0.95_8_None_(1, 2)     tfidf
966     0.8644   0.8_8_10000_(1, 2)     tfidf
777     0.8644    0.7_8_None_(1, 2)     tfidf
779     0.8644   0.7_8_20000_(1, 2)     tfidf
7       0.8644   0.75_5_None_(1, 2)     tfidf
954     0.8644  0.75_8_10000_(1, 2)     tfidf
741     0.8644   0.9_8_25000_(1, 2)     tfidf
715     0.8644  0.85_8_10000_(1, 2)     tfidf
1599    0.8640   0.7_5_15000_(1, 2)     count
1436    0.8640   0.75_5_None_(1, 2)     count
518     0.8640  0.85_1_20000_(1, 3)     tfidf
229     0.8640    1.0_2_None_(1, 2)     tfidf
402     0.8640   0.7_1_20000_(1, 3)     tfidf
799     0.8640   0.7_2_10000_(1, 2)     tfidf
278     0.8640   0.9_5_10000_(1, 3)     tfidf

Лучшие 50 не сильно отличаются , и имею практически одинаковый результат. Как видно лучший результат дает tfidf, хотя в лучшие 50 вошло два count, их результаты совсем немного хуже лучших.  Так же видно, что униформы не попали в топ лучших результатов, привалюруют (1,3) и (1,2). Ограничение на объем слов , дает лучше результаты чем его отсутсвие (из 30000) 25 и даже 10 тысяч лучше чем None. наличие ограничение на максимальную и минимальную частоту в небольших отклонениях мало вляиет на результат  при tfidf, при этом count , удается вырваться только при более сильных ограничениях 0,7 сверху и 5 слов минимум. Как мне видеться основной в клад в результат дает использование tfidf и ngram_range(1,2) и (1,2)
(3,3) дает самый нихкий результат

In [159]:
result.tail(50)

      accuracy                 param vectoreiz
325     0.4992    0.8_40_2000_(3, 3)     tfidf
1278    0.4992   0.75_50_2000_(3, 3)     count
1719    0.4992  0.95_50_10000_(3, 3)     count
96      0.4992   0.7_40_10000_(3, 3)     tfidf
1316    0.4992    0.95_40_100_(3, 3)     count
1904    0.4992    0.7_50_1000_(3, 3)     count
1903    0.4992    1.0_50_2000_(3, 3)     count
280     0.4992   0.95_40_1000_(3, 3)     tfidf
287     0.4992   1.0_40_10000_(3, 3)     tfidf
1895    0.4992   0.7_40_25000_(3, 3)     count
727     0.4992  0.85_50_15000_(3, 3)     tfidf
1873    0.4992    0.9_50_2000_(3, 3)     count
1406    0.4992    0.95_50_500_(3, 3)     count
1358    0.4992    1.0_50_1000_(3, 3)     count
295     0.4992    0.95_40_100_(3, 3)     tfidf
678     0.4992     1.0_40_500_(3, 3)     tfidf
1402    0.4992   1.0_40_15000_(3, 3)     count
1411    0.4992   0.75_50_5000_(3, 3)     count
1868    0.4992  0.85_40_25000_(3, 3)     count
206     0.4972   0.8_30_25000_(3, 3)     tfidf
383     0.4972  0.75_30_10000_(3, 3)     tfidf
243     0.4972     0.8_30_100_(3, 3)     tfidf
219     0.4972  0.75_30_20000_(3, 3)     tfidf
353     0.4972     1.0_30_100_(3, 3)     tfidf
1988    0.4972     0.7_30_500_(3, 3)     count
1035    0.4972    0.7_30_5000_(3, 3)     count
1766    0.4972    0.9_30_1000_(3, 3)     count
207     0.4972     0.9_30_500_(3, 3)     tfidf
1504    0.4972  0.75_30_10000_(3, 3)     count
1012    0.4972   0.95_30_5000_(3, 3)     count
958     0.4972    1.0_30_5000_(3, 3)     tfidf
1280    0.4972   0.7_30_25000_(3, 3)     count
747     0.4972    0.85_30_500_(3, 3)     tfidf
743     0.4972  0.85_30_20000_(3, 3)     tfidf
895     0.4972   0.85_30_5000_(3, 3)     tfidf
897     0.4972    0.9_30_1000_(3, 3)     tfidf
1203    0.4972  0.75_30_25000_(3, 3)     count
655     0.4972   1.0_30_10000_(3, 3)     tfidf
1863    0.4972   0.75_30_1000_(3, 3)     count
1158    0.4972     1.0_30_500_(3, 3)     count
197     0.4972   0.85_30_2000_(3, 3)     tfidf
79      0.4972    0.9_30_5000_(3, 3)     tfidf
533     0.4972   0.95_30_None_(3, 3)     tfidf
998     0.4972    0.8_30_5000_(3, 3)     tfidf
1967    0.4972   1.0_30_20000_(3, 3)     count
1545    0.4972    0.7_30_2000_(3, 3)     count
479     0.4972    0.95_30_500_(3, 3)     tfidf
1563    0.4972   0.9_30_15000_(3, 3)     count
1585    0.4972   0.8_30_15000_(3, 3)     count
1409    0.4972    0.75_30_500_(3, 3)     count